name: Deploy to EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m venv venv  # 가상환경 생성
          source venv/bin/activate  # 가상환경 활성화
          python -m pip install --upgrade pip  # pip 업그레이드
          pip install -r requirements.txt  # requirements.txt에 명시된 패키지 설치
          if [ ! -d "malimo" ]; then
          git clone -b dev https://github.com/ktb-23/malimo-ai.git malimo  # Git 저장소를 /home/ubuntu/malimo에 클론
          fi 
          cd malimo 
          git pull origin dev # Git 저장소 업데이트
          # 가상환경 활성화
          pkill gunicorn || echo "No existing gunicorn process running" 
          nohup venv/bin/gunicorn -w 4 server:app -b 0.0.0.0:5001 > /dev/null 2>&1 

