name: Deploy to EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  # GitHub Secrets에 저장된 SSH 개인 키
        run: |
          echo "$EC2_SSH_KEY" > ~/ec2_key.pem
          chmod 600 ~/ec2_key.pem

          ssh -o StrictHostKeyChecking=no -i ~/ec2_key.pem ubuntu@<EC2_IP_ADDRESS> << 'EOF'
            cd /home/ubuntu/malimo || git clone -b dev https://github.com/ktb-23/malimo-ai.git malimo && cd malimo

            # 가상 환경 설정 및 패키지 설치
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # 최신 코드로 업데이트
            git pull origin dev

            # gunicorn 종료 후 재시작
            pkill gunicorn || echo "No existing gunicorn process running"
            nohup venv/bin/gunicorn -w 4 server:app -b 0.0.0.0:5001 > /dev/null 2>&1 &
          EOF
