name: Deploy to EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd home/ubuntu/malimo 
          python3 -m venv venv
          source venv/bin/activate 
          python -m pip install --upgrade pip 
          pip install -r requirements.txt  
          git pull origin dev 
          pkill gunicorn || echo "No existing gunicorn process running" 
          nohup venv/bin/gunicorn -w 4 server:app -b 0.0.0.0:5001 > /dev/null 2>&1 

